namespace SOLTEC.Core.DTOS;

/// <summary>
/// Represents a problem detail according to RFC 7807 standard for HTTP API error responses.
/// </summary>
/// <example>
/// Example of usage:
/// <![CDATA[
/// var _problem = new ProblemDetailsDto
/// {
///     Type = "https://example.com/validation-error",
///     Title = "One or more validation errors occurred.",
///     Status = 400,
///     Detail = "The Name field is required.",
///     Instance = "/users"
/// };
/// ]]>
/// </example>
public class ProblemDetailsDto
{
    /// <summary>
    /// A URI reference that identifies the problem type.
    /// </summary>
    public string? Type { get; set; }

    /// <summary>
    /// A short, human-readable summary of the problem type.
    /// </summary>
    public string? Title { get; set; }

    /// <summary>
    /// The HTTP status code generated by the origin server for this occurrence of the problem.
    /// </summary>
    public int Status { get; set; }

    /// <summary>
    /// A human-readable explanation specific to this occurrence of the problem.
    /// </summary>
    public string? Detail { get; set; }

    /// <summary>
    /// A URI reference that identifies the specific occurrence of the problem.
    /// </summary>
    public string? Instance { get; set; }

    /// <summary>
    /// A collection of additional key-value pairs containing extra error details.
    /// </summary>
    public IDictionary<string, object> Extensions { get; } = new Dictionary<string, object>();
}
